repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        types: [python]
        entry: pdm run isort . --profile black
        language: system
        pass_filenames: false
        always_run: true
      - id: black
        name: black
        stages: [commit]
        types: [python]
        entry: pdm run black . -t py312 --extend-exclude /data/
        language: system
        pass_filenames: false
        always_run: true
      - id: ruff
        name: ruff
        stages: [commit]
        types: [python]
        entry: pdm run ruff check .  --fix
        language: system
        pass_filenames: false
        always_run: true
        fail_fast: true
