services:
  app:
    build: .
    env_file:
      - .env-development
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:15
    env_file:
      - .env-development
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
