{{- if (not (empty .Values.externalsecrets)) -}}
{{- range $secret_def := .Values.externalsecrets.externalsecrets }}
{{- if (empty $secret_def.disabled) -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secret_def.spec.target.name }}
  namespace: {{ $.Values.namespace }}
  {{- with .labels }}
  labels:
{{ toYaml . | indent 4 }}
{{- end }}
  {{- with .annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{ toYaml $secret_def.spec | indent 2 }}
---
{{ end }}
{{- end }}
{{- end }}
