{{- if (hasKey .Values "externalsecrets") -}}
{{- if (hasKey .Values.externalsecrets "store") -}}
{{- if (empty .Values.externalsecrets.store.disabled) -}}
{{- with .Values.externalsecrets.store -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .name  }}
  namespace: {{ $.Values.namespace }}
  {{- with .labels }}
  labels:
{{ toYaml . | indent 4 }}
{{- end }}
  {{- with .annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  provider:
{{ toYaml .provider | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
